#!/bin/usr/python3
import sys


# RSA FACTORING CHALLENGE

# Function takes an integer n and returns tow smaller integers, p and q
def factorize(n):
    # This loop checks all integers from 2 to n // 2 + 1 to see if they are factors of n. 
    for i in range(2, n // 2 + 1):
        # Check if n is divisible by 'i' without a reminder
        if n % i == 0:
            # If n is divisible by i, then the function returns i and n // i as the factors.
            return i, n // i
    # If no factors are found, return None, None to indicate 'n' is prime.
    return None, None

# Check if the correct number of command-line arguments is provided.
if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

# Get the name of the input file from the command-line arguments.
input_file = sys.argv[1]

try:
    # Open and read the input file.
    with open(input_file, 'r') as file:
        # Go through each line in the file.
        for line in file:
            # Convert line to an integer (if > 1).
            n = int(line.strip())
            # Find the factors 'p' and 'q' using the factorize function.
            p, q = factorize(n)
            if p is not None and q is not None:
                # Print the factorization if both 'p' and 'q' are not None.
                print(f"{n}={p}*{q}")
            else:
                # Print 'n' as a prime number when both 'p' and 'q' are None.
                print(f"{n} is a prime number")

except FileNotFoundError:
    # Manage scenarios involving the absence of the input file.
    print(f"File '{input_file}' not found.")
    sys.exit(1)
except ValueError:
    # Addres invalid data in the input file.
    print("Invalid input in the file. Please make sure all lines contain valid natural numbers greater than 1.")
    sys.exit(1)

